from enum import StrEnum


class PlatformRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"


class BusinessRole(StrEnum):
    BUSINESS_OWNER = "BUSINESS_OWNER"
    BUSINESS_ADMIN = "BUSINESS_ADMIN"
    BUSINESS_MANAGER = "BUSINESS_MANAGER"
    SALES = "SALES"
    EDITOR = "EDITOR"
    STAFF = "STAFF"


class BusinessStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class LeadStatus(StrEnum):
    NEW = "NEW"
    CONTACTED = "CONTACTED"
    QUALIFIED = "QUALIFIED"
    BOOKED = "BOOKED"
    CONVERTED = "CONVERTED"
    LOST = "LOST"


class LeadSource(StrEnum):
    WEBSITE = "WEBSITE"
    WHATSAPP = "WHATSAPP"
    INSTAGRAM = "INSTAGRAM"
    FACEBOOK = "FACEBOOK"
    TIKTOK = "TIKTOK"
    PHONE = "PHONE"
    WALK_IN = "WALK_IN"
    REFERRAL = "REFERRAL"
    QR = "QR"
    OTHER = "OTHER"


class BookingStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class SubscriptionStatus(StrEnum):
    TRIAL = "TRIAL"
    ACTIVE = "ACTIVE"
    PAST_DUE = "PAST_DUE"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    SUSPENDED = "SUSPENDED"


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    SENT = "SENT"
    CANCELLED = "CANCELLED"


class CampaignKind(StrEnum):
    WHATSAPP = "WHATSAPP"
    REACTIVATION = "REACTIVATION"
    NEW_SERVICE = "NEW_SERVICE"
    BIRTHDAY = "BIRTHDAY"
    REVIEW_REQUEST = "REVIEW_REQUEST"
    SPECIAL_OFFER = "SPECIAL_OFFER"
    FOLLOWUP = "FOLLOWUP"
    GROWTH = "GROWTH"


class SalesLeadStatus(StrEnum):
    NEW = "NEW"
    CONTACTED = "CONTACTED"
    DEMO = "DEMO"
    INTERESTED = "INTERESTED"
    ONBOARDING = "ONBOARDING"
    ACTIVE = "ACTIVE"
    LOST = "LOST"


class EventType(StrEnum):
    PROFILE_VIEW = "PROFILE_VIEW"
    WEBSITE_VISIT = "WEBSITE_VISIT"
    WHATSAPP_CLICK = "WHATSAPP_CLICK"
    PHONE_CLICK = "PHONE_CLICK"
    DIRECTIONS_CLICK = "DIRECTIONS_CLICK"
    BOOKING_REQUEST = "BOOKING_REQUEST"
    REVIEW_PAGE_VIEW = "REVIEW_PAGE_VIEW"
    QR_SCAN = "QR_SCAN"
    PRODUCT_VIEW = "PRODUCT_VIEW"
    SERVICE_VIEW = "SERVICE_VIEW"
    SEARCH = "SEARCH"
    ADD_TO_CART = "ADD_TO_CART"
    CHECKOUT_STARTED = "CHECKOUT_STARTED"
    ORDER_PLACED = "ORDER_PLACED"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    PREPARING = "PREPARING"
    READY = "READY"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
