"""website style and settings

Revision ID: 154268b96714
Revises: 6fd144604a30
Create Date: 2026-09-30 16:58:49.501254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154268b96714'
down_revision: Union[str, Sequence[str], None] = '6fd144604a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('theme_overrides', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('websites', sa.Column('settings', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('websites', sa.Column('published_style', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'published_style')
    op.drop_column('websites', 'settings')
    op.drop_column('websites', 'theme_overrides')
    # ### end Alembic commands ###
