"""attribution campaigns qr growth

Revision ID: 316a4ce53b5e
Revises: dc47e05e5897
Create Date: 2026-10-01 08:47:15.599344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316a4ce53b5e'
down_revision: Union[str, Sequence[str], None] = 'dc47e05e5897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_ref', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('campaign', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'campaign', name='uq_qr_campaign')
    )
    op.create_index(op.f('ix_qr_codes_business_id'), 'qr_codes', ['business_id'], unique=False)
    op.add_column('analytics_events', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('analytics_events', sa.Column('session_id', sa.String(length=40), nullable=True))
    op.add_column('analytics_events', sa.Column('campaign', sa.String(length=64), nullable=True))
    op.add_column('analytics_events', sa.Column('path', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_analytics_events_product_id'), 'analytics_events', ['product_id'], unique=False)
    op.create_foreign_key(None, 'analytics_events', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('bookings', sa.Column('campaign', sa.String(length=64), nullable=True))
    op.add_column('businesses', sa.Column('growth_settings', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('customers', sa.Column('acquisition_source', sa.String(length=48), nullable=True))
    op.add_column('customers', sa.Column('acquisition_campaign', sa.String(length=64), nullable=True))
    op.add_column('leads', sa.Column('campaign', sa.String(length=64), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('objective', sa.String(length=16), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('offer_text', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('marketing_campaigns', sa.Column('discount_code', sa.String(length=32), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('target_type', sa.String(length=16), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('target_ref', sa.String(length=64), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('channels', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('marketing_campaigns', sa.Column('content', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('marketing_campaigns', sa.Column('starts_on', sa.Date(), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('ends_on', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('campaign', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'campaign')
    op.drop_column('marketing_campaigns', 'ends_on')
    op.drop_column('marketing_campaigns', 'starts_on')
    op.drop_column('marketing_campaigns', 'content')
    op.drop_column('marketing_campaigns', 'channels')
    op.drop_column('marketing_campaigns', 'target_ref')
    op.drop_column('marketing_campaigns', 'target_type')
    op.drop_column('marketing_campaigns', 'discount_code')
    op.drop_column('marketing_campaigns', 'offer_text')
    op.drop_column('marketing_campaigns', 'objective')
    op.drop_column('marketing_campaigns', 'slug')
    op.drop_column('leads', 'campaign')
    op.drop_column('customers', 'acquisition_campaign')
    op.drop_column('customers', 'acquisition_source')
    op.drop_column('businesses', 'growth_settings')
    op.drop_column('bookings', 'campaign')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('analytics_events_product_id_fkey', 'analytics_events', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_events_product_id'), table_name='analytics_events')
    op.drop_column('analytics_events', 'path')
    op.drop_column('analytics_events', 'campaign')
    op.drop_column('analytics_events', 'session_id')
    op.drop_column('analytics_events', 'product_id')
    op.drop_index(op.f('ix_qr_codes_business_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
