"""plan limits domains seo redirects

Revision ID: 53c71e241358
Revises: 316a4ce53b5e
Create Date: 2026-10-01 09:16:48.354837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c71e241358'
down_revision: Union[str, Sequence[str], None] = '316a4ce53b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_redirects',
    sa.Column('from_path', sa.String(length=200), nullable=False),
    sa.Column('to_path', sa.String(length=500), nullable=False),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'from_path', name='uq_redirect_from')
    )
    op.create_index(op.f('ix_site_redirects_business_id'), 'site_redirects', ['business_id'], unique=False)
    op.add_column('businesses', sa.Column('primary_domain', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('integrations', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('domains', sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('domains', sa.Column('dns_ok', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('domains', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('domains', sa.Column('last_error', sa.String(length=300), nullable=True))
    op.add_column('plans', sa.Column('limits', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('plans', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('websites', sa.Column('og_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'og_image')
    op.drop_column('plans', 'version')
    op.drop_column('plans', 'limits')
    op.drop_column('domains', 'last_error')
    op.drop_column('domains', 'last_checked_at')
    op.drop_column('domains', 'dns_ok')
    op.drop_column('domains', 'is_primary')
    op.drop_column('businesses', 'integrations')
    op.drop_column('businesses', 'primary_domain')
    op.drop_index(op.f('ix_site_redirects_business_id'), table_name='site_redirects')
    op.drop_table('site_redirects')
    # ### end Alembic commands ###
