"""products categories multi sections

Revision ID: 558ee6eff644
Revises: 154268b96714
Create Date: 2026-10-01 06:14:34.249982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558ee6eff644'
down_revision: Union[str, Sequence[str], None] = '154268b96714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_digital', sa.Boolean(), nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'slug', name='uq_product_slug')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.add_column('service_categories', sa.Column('slug', sa.String(length=140), nullable=True))
    op.add_column('service_categories', sa.Column('description', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('service_categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('service_categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('service_categories', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('service_categories', sa.Column('seo_title', sa.String(length=200), nullable=True))
    op.add_column('service_categories', sa.Column('seo_description', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_service_categories_parent_id'), 'service_categories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'service_categories', 'service_categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('website_sections', sa.Column('styles', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('website_sections', sa.Column('published_styles', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('uq_section_website_type'), 'website_sections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_section_website_type'), 'website_sections', ['website_id', 'type'], postgresql_nulls_not_distinct=False)
    op.drop_column('website_sections', 'published_styles')
    op.drop_column('website_sections', 'styles')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('service_categories_parent_id_fkey', 'service_categories', type_='foreignkey')
    op.drop_index(op.f('ix_service_categories_parent_id'), table_name='service_categories')
    op.drop_column('service_categories', 'seo_description')
    op.drop_column('service_categories', 'seo_title')
    op.drop_column('service_categories', 'is_visible')
    op.drop_column('service_categories', 'parent_id')
    op.drop_column('service_categories', 'image_url')
    op.drop_column('service_categories', 'description')
    op.drop_column('service_categories', 'slug')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
