"""order scheduled for

Revision ID: 622699ef2665
Revises: 7d252ec016a3
Create Date: 2026-10-01 11:27:02.862505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622699ef2665'
down_revision: Union[str, Sequence[str], None] = '7d252ec016a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('scheduled_for', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'scheduled_for')
    # ### end Alembic commands ###
