"""connections whatsapp accounts collections courier

Revision ID: 7d252ec016a3
Revises: 53c71e241358
Create Date: 2026-10-01 10:51:20.182322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d252ec016a3'
down_revision: Union[str, Sequence[str], None] = '53c71e241358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'slug', name='uq_collection_slug')
    )
    op.create_index(op.f('ix_collections_business_id'), 'collections', ['business_id'], unique=False)
    op.create_table('customer_otps',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_otps_business_id'), 'customer_otps', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_otps_identifier'), 'customer_otps', ['identifier'], unique=False)
    op.create_table('merchant_connections',
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secrets_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', name='uq_connection_provider')
    )
    op.create_index(op.f('ix_merchant_connections_business_id'), 'merchant_connections', ['business_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('purpose', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_business_phone', 'whatsapp_messages', ['business_id', 'phone', 'created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_business_id'), 'whatsapp_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_provider_id'), 'whatsapp_messages', ['provider_id'], unique=False)
    op.create_table('collection_products',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'product_id', name='uq_collection_product')
    )
    op.create_index(op.f('ix_collection_products_business_id'), 'collection_products', ['business_id'], unique=False)
    op.create_index(op.f('ix_collection_products_collection_id'), 'collection_products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_products_product_id'), 'collection_products', ['product_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('line', sa.String(length=300), nullable=False),
    sa.Column('zone', sa.String(length=80), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_business_id'), 'customer_addresses', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_table('saved_products',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_saved_product')
    )
    op.create_index(op.f('ix_saved_products_business_id'), 'saved_products', ['business_id'], unique=False)
    op.create_index(op.f('ix_saved_products_customer_id'), 'saved_products', ['customer_id'], unique=False)
    op.create_index(op.f('ix_saved_products_product_id'), 'saved_products', ['product_id'], unique=False)
    op.add_column('orders', sa.Column('courier_name', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('courier_phone', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('tracking_url', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('payment_reference', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('payment_provider', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_provider')
    op.drop_column('orders', 'payment_reference')
    op.drop_column('orders', 'tracking_url')
    op.drop_column('orders', 'courier_phone')
    op.drop_column('orders', 'courier_name')
    op.drop_index(op.f('ix_saved_products_product_id'), table_name='saved_products')
    op.drop_index(op.f('ix_saved_products_customer_id'), table_name='saved_products')
    op.drop_index(op.f('ix_saved_products_business_id'), table_name='saved_products')
    op.drop_table('saved_products')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_business_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_collection_products_product_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_collection_id'), table_name='collection_products')
    op.drop_index(op.f('ix_collection_products_business_id'), table_name='collection_products')
    op.drop_table('collection_products')
    op.drop_index(op.f('ix_whatsapp_messages_provider_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_business_id'), table_name='whatsapp_messages')
    op.drop_index('ix_wa_business_phone', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_merchant_connections_business_id'), table_name='merchant_connections')
    op.drop_table('merchant_connections')
    op.drop_index(op.f('ix_customer_otps_identifier'), table_name='customer_otps')
    op.drop_index(op.f('ix_customer_otps_business_id'), table_name='customer_otps')
    op.drop_table('customer_otps')
    op.drop_index(op.f('ix_collections_business_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
