"""commerce pages variants orders discounts

Revision ID: dc47e05e5897
Revises: f663b34cdb56
Create Date: 2026-10-01 06:54:33.231558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc47e05e5897'
down_revision: Union[str, Sequence[str], None] = 'f663b34cdb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=14), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('category_ids', sa.JSON(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('once_per_customer', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_discount_code')
    )
    op.create_index(op.f('ix_discounts_business_id'), 'discounts', ['business_id'], unique=False)
    op.create_table('website_pages',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('published', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'slug', name='uq_page_slug')
    )
    op.create_index(op.f('ix_website_pages_business_id'), 'website_pages', ['business_id'], unique=False)
    op.create_index(op.f('ix_website_pages_website_id'), 'website_pages', ['website_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'title', name='uq_variant_title')
    )
    op.create_index(op.f('ix_product_variants_business_id'), 'product_variants', ['business_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('delivery_method', sa.String(length=12), nullable=False),
    sa.Column('delivery_zone', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('notes', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=12), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_code', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=True),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('stock_restored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number', name='uq_order_number'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index('ix_orders_business_status', 'orders', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('qty_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_business_time', 'inventory_movements', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_business_id'), 'inventory_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_created_by'), 'inventory_movements', ['created_by'], unique=False)
    op.create_index(op.f('ix_inventory_movements_order_id'), 'inventory_movements', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_variant_id'), 'inventory_movements', ['variant_id'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_actor_id'), 'order_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_order_events_business_id'), 'order_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variant_title', sa.String(length=160), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_business_id'), 'order_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_service_id'), 'order_items', ['service_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.add_column('businesses', sa.Column('store_settings', sa.JSON(), nullable=False, server_default='{}' if 'store_settings' == 'store_settings' else '[]'))
    op.add_column('payments', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('options', sa.JSON(), nullable=False, server_default='{}' if 'options' == 'store_settings' else '[]'))
    op.add_column('reviews', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('services', sa.Column('slug', sa.String(length=180), nullable=True))
    op.add_column('website_sections', sa.Column('page_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_website_sections_page_id'), 'website_sections', ['page_id'], unique=False)
    op.create_foreign_key(None, 'website_sections', 'website_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.add_column('websites', sa.Column('navigation', sa.JSON(), nullable=False, server_default='{}' if 'navigation' == 'store_settings' else '[]'))

    # --- data: every existing website gets a Home page that owns its sections; services get slugs
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO website_pages (id, business_id, website_id, slug, title, is_home, enabled, position, published)
        SELECT gen_random_uuid(), w.business_id, w.id, 'home', 'Home', true, true, 0,
               CASE WHEN w.status = 'PUBLISHED' THEN '{"slug": "home", "title": "Home", "enabled": true}'::json ELSE NULL END
        FROM websites w
    """))
    conn.execute(sa.text("UPDATE website_sections s SET page_id = p.id FROM website_pages p WHERE p.website_id = s.website_id AND p.is_home"))
    rows = conn.execute(sa.text("SELECT id, business_id, name FROM services ORDER BY created_at")).fetchall()
    import re, unicodedata
    seen = {}
    for sid, bid, name in rows:
        base = re.sub(r"[^a-z0-9]+", "-", unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().lower()).strip("-")[:60] or "service"
        n = seen.get((bid, base), 0) + 1
        seen[(bid, base)] = n
        conn.execute(sa.text("UPDATE services SET slug = :s WHERE id = :i"), {"s": base if n == 1 else f"{base}-{n}", "i": sid})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'navigation')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('website_sections_page_id_fkey', 'website_sections', type_='foreignkey')
    op.drop_index(op.f('ix_website_sections_page_id'), table_name='website_sections')
    op.drop_column('website_sections', 'page_id')
    op.drop_column('services', 'slug')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_column('reviews', 'product_id')
    op.drop_column('products', 'options')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_column('payments', 'order_id')
    op.drop_column('businesses', 'store_settings')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_service_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_business_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_business_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_actor_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_inventory_movements_variant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_order_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_by'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_business_id'), table_name='inventory_movements')
    op.drop_index('ix_inv_business_time', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index('ix_orders_business_status', table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_business_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_website_pages_website_id'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_business_id'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_discounts_business_id'), table_name='discounts')
    op.drop_table('discounts')
    # ### end Alembic commands ###
